AnswerDotAI/nbdev

README.md
=> typos README

settings.ini
Fixing git_url to point to user's repo.
=> Correction to git_url

nbs/index.ipynb
* addition to getting started that is helpful if someone chooses to create new .ipynb instead of modifying provided sample 
* suggestion to make it clear the best way to import your generated module if storing notebooks anywhere other than project root, without requiring sys.path hacks
=> minor documentation updates 

nbdev/sync.py, nbs/01_sync.ipynb
Replace hard coded 'dev/' path with
nbs_path from the settings file
=> Fix script2notebook function

nbdev/export2html.py, nbs/03_export2html.ipynb
I found people were making mistakes in adding this option by often using a hyphen instead of underscore, so adding this minor change
=> add collapse alias with hyphen

nbdev/templates/hide.tpl
This is related to https://github.com/fastai/nbdev/pull/108
=> Only escape Liquid in Code Blocks

setup.py
**Issue:**
Images are currently not being displayed in pypi home page.
Please refer to: https://forums.fast.ai/t/nbdev-and-other-git-repos/62351/20?u=the_ccalderon
**Tests**:
Not sure how to include a test for the `setup.py` file. 
Please let me know if I missed something and I'll fix it right away.
=> Fixing images pypi

nbdev/export2html.py, nbs/03_export2html.ipynb
=> fixes #123

nbdev/export2html.py, nbs/03_export2html.ipynb
per https://forums.fast.ai/t/fastpages-github-pages-blog-using-nbdev/62828/231
- adds alias for hide_input to include hide-input
- adds multiline detection of flags
- makes flags case insensitive 
cc: @sgugger
=> add multi-line for flags

docs/export.html, nbdev/export.py, nbs/00_export.ipynb
wrt: https://github.com/fastai/nbdev/issues/137
- renamed _add2add to _add2all
- updated docs to include detailed use of `_all_`
- hidden the _add2all test cell - not sure it makes sense to see tests for a function that is not in the docs
=> add2add->add2all and updated docs for extra_add

nbdev/template.py
* `make black`: run black on the exported library
* `make sync`: synchronize changes in the exported library back to the notebooks
=> make black and make sync

docs/_config.yml
@jph00 I thought maybe you fixed this yesterday, but this corrects the issue of URLs resolving to the proper location
=> Fix url construction

docs/_includes/topnav.html
=> Fix home button

nbs/index.ipynb
=> fix typo ref: #224 

.devcontainer.json, docker-compose.yml
Similar to https://github.com/fastai/fastai/pull/2779
=> Enable Codespaces for nbdev

nbdev/export2html.py, nbdev/templates/hide-md.tpl, nbdev/templates/hide.tpl, nbs/03_export2html.ipynb, settings.ini
=> Revert "Updated nbdev to use 6.0 with pre-existing 5.x templates"

nbdev/__init__.py
Sorry @jph00 misread the diff and thought you'd already removed this
=> removed flags import

nbdev/export2html.py, nbs/03_export2html.ipynb
Hi, @jph00 
I think there might be a mistake in the filter condition. 
If not (and I just don't understand it)  just disregard this  PR.
Best regards,
Butch
=> Fix filter condition to match if filename is not 'index.ipynb'

nbdev/showdoc.py, nbs/02_showdoc.ipynb
There appear to be a bug in the code where "IN_NOTEBOOK" is not imported... This now fix the issue.
=> Fix bug where "IN_NOTEBOOK" is not imported.

docs/tutorial.html, nbs/tutorial.ipynb
=> Fix tutorial link to nbs folder

docs/sidebar.json
=> Update sidebar.json to remove conda.html

docs/cli.html, docs/example.html, docs/export.html, docs/search.html, docs/showdoc.html, nbs/example.ipynb
I am incorporating feedback from @AllenDowney as provided in this document https://docs.google.com/document/d/1A0ISsMXsSV9Tc212OiPikF9JtL-3yXzYl0aGDZ0C2ss/edit?usp=sharing
Netlify preview https://5fb6b0d05c656f151b547cc3--nbdev-docs-preview.netlify.app/example.html
cc: @jph00
=> incorporate feedback into minimal example

docs/css/customstyles.css
=> remove redundant css

docs/tutorial.html, nbs/tutorial.ipynb
related to this comment https://github.com/fastai/nbdev/issues/340#issuecomment-750624473 in  #340
=> update tutorial docs to clarify conda vs pip

nbdev/export2html.py, nbs/03_export2html.ipynb
It appears that you want recursive to always = True regardless of settings.ini for docs. 
@jph00 @muellerzr
=> set recursive=True for docs

docs/tutorial.html, nbs/tutorial.ipynb
=> add `git add` instruction to tutorial

nbdev/clean.py, nbdev/export2html.py, nbdev/test.py, nbs/03_export2html.ipynb, nbs/04_test.ipynb, nbs/07_clean.ipynb
closes #357 
cc: @jph00 @muellerzr
=> update cli funcs to use nbglob

docs/tutorial.html, nbs/tutorial.ipynb
=> add docs about dependencies

README.md, nbs/index.ipynb
=> correct toc

docs/tutorial_colab.html, nbs/tutorial_colab.ipynb
cc @jph00 or @hamelsmu, there were some hide tags in there hiding the important git and colab setup commands. Sorry!
=> Remove hide tags from tutorial

.github/workflows/main.yml
=> Temporarily disable macos from CI

nbdev/export2html.py, nbs/03_export2html.ipynb
Fixes duplicate code found in #450
=> fix issue 450

settings.ini
=> Update jupyter client versioning

nbdev/export2html.py, nbs/03_export2html.ipynb
Fixes bug described here: https://forums.fast.ai/t/nbdev-ignoring-recursive-false/87577/2
=> make recursive behavior for `nbdev_build_docs` consistent with `nbdev_build_lib`

README.md, nbs/index.ipynb
=> update install instructions for windows users

nbdev/export2html.py, nbs/03_export2html.ipynb
=> Prevent to copy images with `attachment:`

nbdev/export2html.py, nbs/03_export2html.ipynb
Removes .html names from sidebar.
Fixes html 404 on gitlab hosting
you can check here:
https://thomas.capelle.gitlab.io/nbdev_template/
=> Docs nav doesn't work on gitlab

nbdev/export2html.py, nbdev/templates/hide-md.tpl, nbdev/templates/hide.tpl, nbs/03_export2html.ipynb, settings.ini
=> Upgrade to nbconvert 6

nbdev/export.py, nbdev/showdoc.py, nbs/00_export.ipynb, nbs/02_showdoc.ipynb, nbs/sync.html
=> Fix show doc for keywords.

nbdev/shortcuts.py, nbs/16_shortcuts.ipynb
cc: @jph00 
I tested it and it works
=> use `curl` instead of `wget`

nbs/getting_started.ipynb, nbs/index.ipynb
=> fix copyright

README.md, nbs/getting_started.ipynb
=> fix code of conduct link

nbdev/cli.py, nbs/10_cli.ipynb
=> missing import

nbs/migrating.ipynb
Added note to migration guide indicating that styles.css needs to be moved inside of nbs_path if there is a custom nbs_path in settings.ini.
=> Add nbs_path migration note

nbdev/clean.py, nbs/11_clean.ipynb
The tuple comparison fails on files which aren't notebooks. First we
need to check the type, then we need to check the version
=> non-notebooks do not have nbformat field

nbdev/processors.py, nbs/09_processors.ipynb, settings.ini, setup.py, tests/2020-09-01-fastcore.ipynb
This is related to #649 
This PR has helper functions that will take fastpages front matter and adapt it to quarto front matter
=> helpers to convert fp front matter to quarto front matter

nbdev/merge.py, nbs/06_merge.ipynb
=> nbdev merge updates

nbdev/processors.py, nbs/09_processors.ipynb
=> add image path compatibility with fastpages

nbdev/cli.py, nbs/10_cli.ipynb
For preview images and social cards: https://quarto.org/docs/websites/website-tools.html#preview-images
=> add site url

nbdev/clean.py, nbs/11_clean.ipynb
@jph00 I'm purposefully not labelling this since its captured by title of https://github.com/fastai/nbdev/pull/784
=> get `jupyter_hooks` from config relative to notebook path

nbdev/merge.py, nbs/06_merge.ipynb
=> `nbdev_merge` fails on `git stash pop` conflict

.github/workflows/test.yaml
=> Create test for docs build

nbdev/release.py, nbdev/showdoc.py, nbs/08_showdoc.ipynb, nbs/17_release.ipynb, nbs/styles.css
cc @hamelsmu @jph00. I'm curious to hear your thoughts on d0d8d2751cb74d71bc720d021ad59438ffe00c6a in particular
- fix #771
- fix #807
- fix #808
=> `show_doc` improvements

nbs/tutorial.ipynb
=> Add example of Mermaid in the tutorial

nbdev/processors.py, nbs/09_processors.ipynb
closes #802 
@jph00 @seeM 
Example of new error message
```
Exception: Error in notebook: processors in cell 105 :
import pandas
assert 5 ==10
```
=> show title if nbdev_filter errors

nbs/tutorial.ipynb
=> add quarto section back to tutorial

nbdev/tutorial.py, nbs/tutorial.ipynb
fix #785 - cc @hamelsmu @jph00
=> refactor tutorial: make your first edit

nbdev/doclinks.py, nbs/04b_doclinks.ipynb
=> Ignore .ipynb_checkpoints folder in module dir

nbdev/showdoc.py, nbs/08_showdoc.ipynb
=> Escape Footnotes from Docments Table

nbdev/showdoc.py, nbs/08_showdoc.ipynb
=> fix `show_doc` signature whitespace removal

nbdev/cli.py, nbs/12_cli.ipynb
=> Allow specifying port for preview

nbdev/cli.py, nbdev/config.py, nbs/01_config.ipynb, nbs/12_cli.ipynb
Think this only affects dev, cc @hamelsmu @jph00
=> fix bootstrapped export in `01_config.ipynb`

nbdev/process.py, nbs/03_process.ipynb
Cell magic, if it exists is always the first line of code in a cell.  Our directives should be able to work with this
This was reported in https://github.com/quarto-dev/quarto-cli/issues/578#issuecomment-1219952007
cc: @jph00
=> allow nbdev directives to work with cell magic

nbs/01_Tutorials/tutorial.ipynb
=> add tutorial alias

nbs/01_Tutorials/01_tutorial.ipynb
=> fix emoji nit

nbdev/sync.py, nbs/05_sync.ipynb
Fixes #775 
I was surprised this was the fix, but it was for me.  I've tested it a bunch
cc: @jph00 @seeM
=> Correct cell index in `nbdev_update`

nbdev/process.py, nbs/01_Tutorials/03_modular_nbdev.ipynb, nbs/09_API/03_process.ipynb
=> "Modular nbdev" tutorial: How to use nbdev's various tools separately

nbs/_quarto.yml
=> Rm Jeremy dir

nbdev/maker.py, nbs/09_API/02_maker.ipynb
There was another instance where the fix for #953 was required.
=> Extended fix 953

nbs/Tutorials/best_practices.ipynb
It might be nicer to view at https://seem.github.io/nbdev/Tutorials/best_practices.html, or to clone this branch of my fork and `nbdev_preview` locally
=> Add tutorial: "Best practices for notebook development"

nbs/Explanations/directives.ipynb
=> Remove reference to notest

nbs/blog/posts/2022-07-28-nbdev2/index.qmd
=> make screenshot bigger -> go outside margins

nbdev/migrate.py, nbs/api/migrate.ipynb, tests/2022-09-06-homeschooling.md
=> fix alias bug

nbdev/doclinks.py, nbs/api/doclinks.ipynb
[Minimal example](https://forums.fast.ai/t/nbdev-v2-launched/97821/130?u=seem)
=> fix exporting `patch_to` which is decorated with `staticmethod`

nbs/migrating.ipynb
=> add deploy.yaml to migrate

nbs/migrating.ipynb
cc: @jph00 @seeM 
Adding additional steps discovered when migrating [Johno's repo](https://github.com/johnowhitaker/cclddg/)
=> Add additional pages and actions setup steps in migration

nbs/images/circles.svg.py
=> Don't use generics - breaks on Python 3.8

nbdev/clean.py, nbs/api/clean.ipynb
=> Write to stdout

nbdev/quarto.py, nbs/api/quarto.ipynb
fixes #1106 
Also fixes https://github.com/fastai/nbdev/issues/1140
=> fix copying of index assets

nbs/tutorials/tutorial.ipynb
=> Update tutorial with note about nbs folder

nbs/tutorials/best_practices.ipynb
=> Add note about unions

nbs/tutorials/blogging.ipynb
cc: @seeM @jph00 
closes #1173
=> add instructions on creating a blog w/quarto

nbs/tutorials/tutorial.ipynb
Ref: https://nbdev.fast.ai/tutorials/tutorial.html#upload-to-pypi
=> Complete sentence on uploading project to pypi

nbdev/processors.py, nbs/api/processors.ipynb
=> fix: key error if widgets is missing `state`

nbdev/doclinks.py, nbs/api/doclinks.ipynb
=> fix: incorrect regex pattern for setting `output-file`

nbdev/quarto.py, nbs/api/quarto.ipynb
=> end `sidebar.yml` with newline

setup.py
could agplv3 be included, it's a good licence for software that might be used in cloud settings
=> add agplv3 license

nbs/tutorials/blogging.ipynb
The PR fixes a minor href in the blogging nb. @jph00
=> fixes #1274

nbs/tutorials/extensions.ipynb
Adds a new extensions tutorial on how to write a very simplistic example just modifying markdown cells. 
cc @hamelsmu @jph00 @seeM
=> Add extensions tutorial

nbs/tutorials/extensions.ipynb
=> Slight nit on the tutorial code

nbs/explanations/directives.ipynb
=> Remove export-other from directives doc

nbs/tutorials/best_practices.ipynb
One tip added to Best Practices.
=> Added note that lists require blank lines before them

nbdev/release.py, nbs/api/18_release.ipynb
This PR documents how to use nbdev to upload the package to TestPypi and custom/private repositories
=> Doc TestPypi upload

nbdev/quarto.py, nbs/api/14_quarto.ipynb
This PR adds a minor docstring for `nbdev_readme`. cc @jph00
=> fixes #1364

nbdev/quarto.py, nbs/api/14_quarto.ipynb
Fixed problem for Windows, which I described below, by simply hiding import inside necessary function.
https://github.com/fastai/nbdev/issues/1382
=> moved uname into func to fix Windows import error

nbdev/cli.py, nbs/api/13_cli.ipynb
See template [issue 13](https://github.com/fastai/nbdev-template/issues/13)
=> add repo and tag options to nbdev_new`

nbdev/cli.py, nbs/api/13_cli.ipynb
Hello!
This is the fix for error mentioned in the issue: https://github.com/fastai/nbdev/issues/1412#issue-2273366125
=> fixes #1412

README.md, nbs/getting_started.ipynb
This PR updates the README to show the newly added console scripts in the package. cc @jph00
=> update readme to show new console_scripts
