AnswerDotAI/nbdev

- docs/_config.yml
- nbdev/template.py
When trying to deploy the nbdev documentation to an authenticated heroku app (using https://github.com/benbalter/jekyll-auth) it turned out that the extensionless URLs in the menu didn't work. When I manually added `.html` to the end of the URL I did find the page.
This was easily fixed (although it took some time to find this solution) by adding a parameter `permalink: pretty` to `_config.yml`.
> Add permalink: pretty as default option in the _config.yml template.

- docs/showdoc.html
- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
- settings.ini
In our existing codebase, we like having detailed doc strings. With the current behaviour, documentation is pretty but docstrings lose their newlines/indentation, which is a problem for most of the common ways of formatting arguments. This adds a `monospace_docstrings` config option that adds `<pre>` tags around the doc strings.
> add option to format docstring as monospace

- docs/export2html.html
- nbdev/export2html.py
- nbs/03_export2html.ipynb
Changed the double quotes in the `add_jekyll_note` function by single quotes escaped (using `\`). I also updated the test case and added an example of a doc link in a Jekyll note to show that it works now.
Tested this for the nbdev docs as well as for my own docs (where I initially encountered the problem) and it seems to solve the problem in both cases.
Solves #40
> Fix jekyll note doclinks

- nbdev/cli.py
- nbs/06_cli.ipynb
Sometimes I copy a Notebook and I forget to change the title, this has caused me some confusion as to why the sidebar apparently was not generated properly. I thought it might be useful to add a simple warning if you are using the same title multiple times when generating the sidebar (as you probably never intend to do this).
Please let me know if you think this is useful, or if I should implement this in another way.
> Add a warning in case some notebooks have a duplicate Title.

- nbdev/cli.py
- nbs/06_cli.ipynb
Added a print statement to note that a specific notebook is being converted to README.md (I was looking for a way to make sure readme was updated for #53). 
The only change in the behavior is the last line here: 
```
nate-macbook:~/c/nbdev chore/make_readme_print nbdev_build_docs                                                                                     (nbdev)
converting: /Users/xnutsive/code/nbdev/nbs/01_sync.ipynb
.... 
converting: /Users/xnutsive/code/nbdev/nbs/05_merge.ipynb
converting /Users/xnutsive/code/nbdev/nbs/index.ipynb to README.md
nate-macbook:~/c/nbdev chore/make_readme_print
```
> Print which file got converted to README.md in build_docs

- nbdev/cli.py
- nbs/06_cli.ipynb
Building the `fastscript` docs I realized that the `index.ipynb` can have the same title as another notebook (in this case `00_core.ipynb`) and it shouldn't give a warning. This small change should fix that.
> Don't give a warning if the index notebook has a duplicate title

- nbdev/export2html.py
- nbs/03_export2html.ipynb
I found this bug when I tried to export docs from 2 notebooks named `02_gpt2_lm.ipynb` and `03_lstm_lm.ipynb`.
There is only one html file called `lm.html` be generated from those 2 notebooks.
Therefore I dig into the code in _nb2htmlfname and try to fix it.
The only thing I change is the _re_digits. 
Just add a question mark after greedy match S* and also add a test that check 00ab_export_module_1.ipynb can be transformed to export_module_1.html correctly.
Thanks.
> fixes bug that _nb2htmlfname would generate 1.html from 00ab_export_module_1.ipynb

- nbdev/export2html.py
- nbs/03_export2html.ipynb
`exporter` is not a callable
cc: @sgugger
> Fix Minor Bug in export2html.convert_nb

- nbdev/export2html.py
- nbs/03_export2html.ipynb
I noticed that we aren't calling _nb2htmlfname with the dest parameter here, updating for consistency.
> Call _nb2htmlfname with dest parameter

- settings.ini
Fixes an issue with older versions of nbconvert - looks like prior to 5.6.1 or so - that have 'resources' as a required argument to the preprocess function, resulting in errors like this when running tests:
`preprocess() missing 1 required positional argument: 'resources'`
Is this the only place the version would need to be updated?
nbconvert commit for the API change:
https://github.com/jupyter/nbconvert/commit/ad6d34b563d1a137a19173c149b85fc11876e2d8
> Set min nbconvert version due to API change

- nbdev/export2html.py
- nbs/03_export2html.ipynb
I encountered an error in my testing
> UnboundLocalError: local variable 'passed' referenced before assignment
This was because previously if no notebooks changed, then the variable `passed` would not have been created
> correct else statement

- nbs/index.ipynb
This fixes a very minor typo that jumped out at me while reading the documentation homepage: `form` -> `from`.
> Minor: fix typo in index.ipynb

- nbdev/export2html.py
- nbs/03_export2html.ipynb
The result of `glob.glob(fname)` is a List[str], which caused an error because later on expects List[Path]
Learned about this error when trying to reproduce https://github.com/fastai/fast_template/issues/18
Without this fix will get this error:
```
AttributeError: 'str' object has no attribute 'name'
```
> Fix minor error in else statement

- nbdev/templates/jekyll.tpl
escape `{{` curly braces that might be in HTML
I've encountered this while using this template, and this helps to guard against this situation where it may cause a problem with liquid
> escape `{{` curly braces that might be in generated HTML from notebook

- .github/workflows/main.yml
@sgugger this will help solve the problem to catch things like what happened in #73
You will also have to turn on branch protection.   In settings, create a branch protection rule for the `master` branch and check `Require Status Checks To Pass Before Merging`
> Enable CI on Pull Requests

- nbdev/imports.py
__Config.\_\_init\_\_ assert message updated__
The message on the failed assert for existence of settings.ini refers to a non-existing Config.create method. In the notebooks create_config is used, and I have update the assert message accordingly.
> Updated file exists assertion message to point to the correct function.

- nbdev/cli.py
- nbs/06_cli.ipynb
Bug happened when I try to use nbdev_new in the directory including space like "/gdrive/My Drive/xxx".
Fix it by not using split() at target path.
> fix nbdev_new when path including space

- nbdev/export.py
- nbs/00_export.ipynb
Hi again,
I'm working a lot with ctypes at the moment, which is why it's much easier in the long run to write code where most things have type annotations on them.
I've noticed however, that when I declare a global variable with a type hint e.g. `a:int = 1`, the name that's added to `__all__` is not `'a'` as one might expect, but `'a:int'`.
This causes any code that is trying to import that module to crash, because `'a:int'` is not valid python syntax for a variable name.
This PR is fixing this particular case, and a few other things I spotted along the way.
I hope this will be useful to people.
Here is a __changelog__ of everything that's changed. All changes were made in `nbs/00_export.ipynb`:
- Add a test case to `_re_patch_func` to check that type annotations, including return types, …
> Improve support for pythons type hint syntax (pep 484)

- nbdev/export2html.py
- nbs/03_export2html.ipynb
- nbconvert injects the ugly ¶ symbol as text in anchor tags.
- nbdev ignores the ¶ using CSS by [setting display value to none](https://github.com/fastai/nbdev/blob/c41b7e6b85ae452fb1d9eeb5fe7077275eb0c1ef/docs/css/customstyles.css#L1-L3) and uses anchor.js to apply beautiful styling. 
- However, these ugly ¶ show up in fastpages, and I'm using javascript to remove them.  This seems like the best way to remove this text.   It is useful to remove this text b/c it shows up in search results.
cc: @sgugger
> remove anchor tag text

- nbdev/imports.py
On windows the root of the file tree is a drive letter (e.g. `'C:/'`), meaning the `cfg_path != Path('/')` check can never be false, causing an infinite loop when no settings.ini exists.
> Change Linux specific check to also work on other platforms

- nbdev/export2html.py
- nbs/03_export2html.ipynb
You accidentally used `{{% raw %}}` instead of `{% raw %} `
See https://shopify.github.io/liquid/tags/raw/
I pulled my hair out for hours trying to figure out what was going wrong.  Luckily I finally was able to "see" the double curly braces!  Wooo 🙇 
@sgugger do you mind cutting another release?
> fix liquid tags only one curly brace

- nbdev/export2html.py
- nbdev/templates/hide.tpl
- nbs/03_export2html.ipynb
cc: @sgugger 
- Fixed `#hide_output` flag, the scaffolding was there but wasn't being implemented AFAIK?
- Added `#collapse_output` flag, with documentation.  Alias is `#collapse-output`
This PR closes https://github.com/fastai/nbdev_template/issues/12
> Fixed #hide_output and added #collapse_output flag

- nbdev/export.py
- nbs/00_export.ipynb
I believe `__all__` and `_nbdev.py` were not correct due to extra decorators being between `@patch` and the function definition.
This should fix it.
Another test has been added.
> fix: allow use of other decorators below patch

- docs/_config.yml
Removing ending "/" for correct URL
#Related Issue
#126 Local Jekyll rendering incorrectly with extra `/`
> Local Jekyll rendering incorrectly with extra `/`

- nbs/01_sync.ipynb
in
`assert len(splits)==len(dic[key]), f\"Exported file from notebooks should have {len(dic[fname])} cells but has {len(splits)}.\"`
what's checked is `len(dic[key])` but what's reported in assertion failure message is `len(dic[fname])`. since `dic` is
a defaultdict, it's just happy to output the incorrect `0`
> _script2notebook: assertion wrongly reports '0' for expected number of cells

- nbs/index.ipynb
- nbs/tutorial.ipynb
Be clearer that `nbdev` needs to be installed in the same environment as
used by the Jupyter Server and any terminal sessions.
Fixes #141
> Installation and Tutorial clarifications

- .github/workflows/main.yml
Following the problem reported in #149 , add a bit more information on the error message when git status is not clean so users facing the same problem are provided with a course of action to try and fix it.
> helpful msg for git status error

- nbdev/templates/hide-md.tpl
- nbdev/templates/jekyll-md.tpl
- nbdev/templates/md.tpl
some details that might help review
- hide-md.tpl is a copy of hide.tpl - with a few differences
- the zero indent of the `details` tags is important - they won't render properly if we indent like in hide.tpl
- we need {{ '' }} after </details> or the next part (usually some output) is not rendered correctly
- I removed the `{% block output_area_prompt %}` section - as this comes from basic.tpl
- I removed the `{% block codecell %}` section - this caused "{% raw %}" to be rendered in the md
> fix issue #156

- nbdev/export2html.py
- nbs/03_export2html.ipynb
Hope you're ok with this simple approach. I tried a few other things but they ended up getting pretty complicated when trying to handle imports that span multiple lines etc
Note: I needed to make `_re_show_doc` a little more specific before using it in `ExecuteShowDocPreprocessor` - otherwise it picks up too many things - this is probably better for `hide_cells` too
> fix issue 171

- README.md
- docs/cli.html
- nbdev/cli.py
- nbs/06_cli.ipynb
Enable option to pass in custom git template repository url by setting `--template_git_repo`. 
```
usage: nbdev_new [-h] [--template_git_repo TEMPLATE_GIT_REPO] [--xtra XTRA] name
Create a new nbdev project with a given name.
positional arguments:
name                  A directory to create the project in
optional arguments:
-h, --help            show this help message and exit
--template_git_repo TEMPLATE_GIT_REPO
url to template repo (default: https://github.com/fastai/nbdev_template.git)
--xtra XTRA           Parse for additional args
```
> add option to use custom git template

- nbdev/clean.py
- nbs/07_clean.ipynb
This is to allow the usages of tags in notebooks to also be in the repo when using the nbdev githooks.
> added tags to cell_metadata_keep

- nbdev/export2html.py
- nbs/03_export2html.ipynb
`_re_import` now has stricter matching conditions for imports, so that it will not match `from xxxx` without the following `import`. This prevents code blocks that include things like
```py
query="""
select *
from database
"""
```
from running when generating docs due to the misclassification of it being imports. 
This can be a conner case, but the stricter condition would not miss any legitimate imports so it shouldn't hurt anything.
> Stricter pattern matching for imports

- nbdev/flags.py
really sorry @jph00 we need this change to fix https://forums.fast.ai/t/create-config-when-pip-install-uqq-fastbook/78340/6
all the colab testing i did last week was on full nbdev projects )o: i'll add "nbdev import from a standalone nb" to my pre-PR checklist
> allow nbdev imports when not in an nbdev project

- nbdev/export2html.py
- nbs/03_export2html.ipynb
With the default project structure, the glob() in notebook2html() can easilly find a copy of a .ipynb file in .ipynb_checkpoints. In this case, running nbdev_build_docs will fail, assuming the .ipynb imports the project (the relative path is not correct from this dir.) The current code to skip hidden path components searches for '/.', whereas str(f) will return the Windows backslash path, so the search will fail. f.as_posix() returns a '/' delimited path on all platforms.
I verified failure of nbdev_build_docs before the fix, and success after installing the fix.
> Fix: correct notebook2html path operation for Windows.

- nbdev/export2html.py
- nbs/03_export2html.ipynb
We need ability to skip execution of notebooks in fastpages.  Discussed in discord : https://discordapp.com/channels/689892369998676007/689892370002870284/753640345731989524
> add option to not exec nb for fastpages

- nbdev/export2html.py
- nbdev/templates/hide-md.tpl
- nbdev/templates/hide.tpl
- nbs/03_export2html.ipynb
- settings.ini
I believe this fixes all the issues for nbconvert 6.0 usage.
I left the templates in 5.x style and used the template_file backwards compatibility supported path for referencing them to keep the PR minimal. NBconvert 6.0 introduced templates as a directories so that it can include config files and multiple jinja files that can be composed as a unit. https://nbconvert.readthedocs.io/en/latest/customizing.html has guides on how this works and how to extend it now if you wish to change to the new pattern.
`make test` complains about `06_cli.ipynb` where the id fields of the two values don't match. But this is happening for me on master with nbconvert 5.6.1 so I think it's unrelated.
`jupyter_client` was given a min version because it's caused issues for other libraries where the min version …
> Updated nbdev to use 6.0 with pre-existing 5.x templates

- nbdev/export2html.py
- nbs/03_export2html.ipynb
As discussed in #263 this makes it such that source code appears below the related heading instead of above the heading.  This is an example of how it looks 
Will do a separate PR for collapsible headings, but want to make sure this is what is desired first.   ﻿
> Place source code below heading on #exports

- nbs/tutorial.ipynb
Hi,
I am proposing to change the instructions in `tutorial.ipynb` to specify the `requirements` in `settings.ini`.
Specifying the `requirements` in `settings.ini` as described in [install_requires in setuptools](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires) leads to a parse error in the build within GitHub Actions.
The link given in `tutorial.ipynb` implies the following format:
```python
requirements = ['fastcore>=1.0.5', 'torchvision<0.7', 'matplotlib']
```
which would lead to a parse error. 
A format that does _not_ cause a parse error is
```python
requirements = fastcore>=1.0.5 torchvision<0.7 matplotlib
```
> Add example for specification of requirements to tutorial.ipynb

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
**I checked all the filenames in fastai/fastai and this fix would fix the following bugs.  All other URLs stay exactly the same.**
NEW URL | OLD URL
-- | --
https://docs.fast.ai/torch_core | https://docs.fast.ai/torch.core
https://docs.fast.ai/tutorial.medical_imaging | https://docs.fast.ai/tutorial.medical.imaging
https://docs.fast.ai/test_utils | https://docs.fast.ai/test.utils
https://docs.fast.ai/pytorch_doc | https://docs.fast.ai/pytorch.doc
_P.S. I'm not sure the best way to add an additional test for this, as I would have to either import fastai which I don't want to add that dependency to nbdev, and to create some kind of new fake code that I export which I don't want to do either._
> fix docs link bug

- nbdev/sync.py
- nbs/01_sync.ipynb
current nbdev parsing does not handle cases where the import are as follow:
```
from lib.a    import *
from lib.bla import c
```
The reason being that the custom spacing after `lib.a` is not supported in the regex.
Added multi-space to the regex, and added test for verification.
> Added support for imports with custom spacing

- nbdev/sync.py
- nbs/01_sync.ipynb
This closes #341 
The issue is that understandably some folks are using `nbdev_update_lib` to convert notebooks when they should be using `nbdev_build_lib`.  I made the following changes:
1. Changed the help docs of the CLI because it was wrong:
- was "A notebook name or glob to convert"
- changed to "A python filename or glob to convert"
2. Raise a warning if you try to pass in a file or glob ending with `.ipynb` as an argument to `nbdev_update_lib`
@jph00 ready for review
> change help string and raise error if wrong input

- nbs/00_export.ipynb
Closes #332 
@jph00 I believe how to use `#export` is best demonstrated by example, so I linked to an external notebook where this is demonstrated.  LMK what you think. 
(It is a bit tricky to show export without actually exporting this is why I used an external repo)
> added examples of #export

- nbdev/cli.py
- nbs/06_cli.ipynb
Changes made
- Instead of files.fast.ai, we get nbdev template files from the latest release asset files of fastai/nbdev_template
- Get branch name from the github api
I tested this locally with multiple scenarios (new repos, existing repo, when files are present, when they aren't present, etc). 
closes #383 
@jph00 ready for review
> nbdev_new: get template from latest release asset

- nbdev/export.py
- nbs/00_export.ipynb
Fixes #388 
cc: @jph00 @muellerzr
> fix recurse issue

- nbdev/test.py
- nbs/04_test.ipynb
> add err msg for attempted tests without any files

- docs/sync.html
- nbdev/sync.py
- nbs/01_sync.ipynb
> fix default arg issue with nbdev_update_lib

- nbdev/export.py
- nbdev/export2html.py
- nbs/00_export.ipynb
- nbs/02_showdoc.ipynb
- nbs/03_export2html.ipynb
It turns out that uncommenting and putting `recursive=False` explicitly was not handled correctly.  
This fixes #423
> Fix recursive flag

- settings.ini
Pin Jupyter client at prior version to fix #454 #456 temporarily.  
We probably need to figure out a long-term solution, however.  cc: @jph00
> Pin Jupyter client version to avoid coroutine error 

- nbdev/clean.py
- nbdev/export.py
- nbdev/export2html.py
- nbdev/sync.py
- nbdev/test.py
- nbs/00_export.ipynb
- nbs/01_sync.ipynb
- nbs/02_showdoc.ipynb
- nbs/03_export2html.ipynb
- nbs/04_test.ipynb
- nbs/07_clean.ipynb
clean up all instances of wherever recursive is mentioned.  With this change, all recursive behavior is controlled by `settings.ini`.   Previously, this behavior was not consistent.  I did a detailed audit of the nbdev library to 
- move the references to the config file upstream into `nbglob`
- remove all necessary downstream code attempting to set a `recursive` argument manually (except for tests).
- Make sure that anywhere nbglob is used, we can expect consistent behavior.
> clean up all instances of recursive

- nbs/tutorial.ipynb
Github Page settings were moved and this reflects that change in the tutorial.  
There's currently a link to the new location where Pages settings used to be - though no idea how long they plan to leave that in the UI.
I am also unsure of if there is anywhere else other than the tutorial this change should be made.
> updating tutorial instructions for github UI change

- nbdev/export2html.py
- nbs/03_export2html.ipynb
These changes will change the logging message to look like this:
```
WARNING: The title: "Title" appears in 2 pages:
['/Users/hamel/github/fastai/docs/data.load.html', '/Users/hamel/github/fastai/docs/camvid.html']
```
@jph00 ready for review
> better logging for duplicate titles

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
Solves https://github.com/fastai/nbdev/issues/587 by having `type_repr` use `_format_annos` rather than `get_name`
The other option to consider is just completely change how `get_name` works and have it be `_format_annos.inner`
cc @jph00 
(Also mark this as Enhancement)
> Fix repr issue with `show_doc`

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
Fixes a variety of bugs pointed out in the discord including:
- Defaults of `None` showing as double backticks
- Parameter names link to types
Refactored slightly where we grab monospace.
(There may be a merge conflict with https://github.com/fastai/nbdev/pull/582 which should be merged before this. If so will address and fix)
> Misc bug fixes + tests

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
Fixes a bug where `cls` and `self` were always popped if present, a lazy approach to testing if it's a method in a class  or not. This PR addresses this and provides a fix. Also fixes a slight error with `get_config` right now (see note in Discord on this). Should be merged after https://github.com/fastai/fastcore/pull/394
> Better checks for cls and self

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
Fixes a bug pointed out in discord where if it's a numerical type, we ignore the decimals and just return the string representation of it in `_format_annos`
This can also be a special case as numbers would be the only time outside of a import we'd expect a decimal to show as the original decimal, as well as if there's a string as a default it should just show the string!
cc  @jph00
> Fix decimal bug

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
Closes https://github.com/fastai/nbdev/issues/603
Previous behavior was to disregard the library if we had a typing such as `typing.Union[int, float]`. But due to the fact these can be nested (such as `Union[List[str],str]` would be, `typing.Union[typing.List[str], str]`), it's better to just keep the library / module inside it.
cc @jph00
> Keep module in name when getting the "qualname"

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
Slightly changes default behavior in `doc`
Current default is to always show docments, even if no docments are present when doing `doc(elt)`, it should be `False` to mimic `show_doc` behavior and only show docments if they are available. Also removed :int typehint (unsure when this was added, dug through commits and still couldn't find where/when)
cc @jph00
> Change doc() default for docments

- docs/Gemfile
Building docker-compose image on WSL2 throws exception
`
nbdev-jekyll-1    | /var/lib/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in require: cannot load such file -- webrick (LoadError)
`
Addition of
`
gem "webrick", "~> 1.7"
`
into `Gemfile` solves the problem.
> Added webrick spec to Gemfile.

- nbs/03_export2html.ipynb
The notebook metadata has a kernelspec section which defines the kernel
to use with the notebook:
```
...
"metadata": {
"jupytext": {
"split_at_heading": true
},
"kernelspec": {
"display_name": "Python 3 (ipykernel)",
"language": "python",
"name": "python3"
},
...
```
Instead of hard coding the kernel name to "python3" we use the default
behavior of using the kernel that the notebook was run with.
See: https://forums.fast.ai/t/modulenotfounderror-in-fresh-conda-environment/93666
> Use the kernel defined in the kernelspec

- nbdev/showdoc.py
- nbs/02_showdoc.ipynb
`show_doc` couldn't show dataclasses (see for example #595). The problem is to show class, nbdev actually shows its constructor and dataclass doesn't have an accessible one. The PR temporary fixes this. The remaining problem is class level docments and class constructor arguments docments are not shown. This needs to be treated in fastcore.docments.
> Fix show_doc for dataclass

- settings.ini
nbdev requires newer fastcore version >= [1.4.5](https://github.com/fastai/fastcore/releases/tag/1.4.5) to build lib, due to docments changes
With fastcore v1.4.4 command `nbdev_build_docs` raises error:
```
Traceback (most recent call last):
File "/usr/local/bin/nbdev_build_lib", line 5, in <module>
from nbdev.export2html import nbdev_build_lib
File "/usr/local/lib/python3.7/dist-packages/nbdev/export2html.py", line 15, in <module>
from .showdoc import *
File "/usr/local/lib/python3.7/dist-packages/nbdev/showdoc.py", line 12, in <module>
from fastcore.docments import _docments, isclass, _clean_comment, _tokens, _param_locs, _get_comment
ImportError: cannot import name '_docments' from 'fastcore.docments' (/usr/local/lib/python3.7/dist-packages/fastcore/docments.py)
```
> Update min fastcore requirement

- nbdev/export.py
- nbdev/showdoc.py
- nbs/00_export.ipynb
- nbs/02_showdoc.ipynb
This fixes `show_doc` for properties, and adds a smoke test. There's a missing `else` branch in the nested if statements.
nbdev + fastcore + fastai tests pass locally.
> fix show_doc for properties

- nbdev/clean.py
- nbs/11_clean.ipynb
It seems like there is a missing return statement when reading from stdin.
The current code reads from stdin and writes to stdout, but then proceeds to
running through all notebook files via globbing and processing all of them.
When git builds the index (happens even during git status) it passes all
files to the filter each via stdin which leads to n^2 behavior where n
is the number of notebooks.
@jph00
> Add early return

- nbdev/clean.py
- nbs/11_clean.ipynb
- tests/metadata.ipynb
Certain tooling puts useful information in the metadata and cell metadata
sections. nbdev_clean currently wipes out everything except some hardcoded
keys.
Allow the user to specify additional keys via settings.ini
Fixes: #600
cc: @jph00
> Allow clean to keep some metadata keys

- README.md
- nbs/11_clean.ipynb
- nbs/getting_started.ipynb
Changed a couple of references to the old `nbdev_install_git_hooks` instead of `nbdev_install_hooks`.
Some issue still remains when previewing the documentation with `nbdev_preview`, all notebooks are stripped of the numbering prefix, except for `11_clean.ipynb`. (See screenshots below), which breaks the autogenerated cross references in the docs (which point to `clean.html` instead of `11_clean.html`)
I haven't been able to locate why that's going on yet.
> Fix nbdev_install_hooks references in the docs

- nbdev/shortcuts.py
- nbs/16_shortcuts.ipynb
This is needed for CI to install quarto for mac
This will close https://github.com/fastai/nbdev/issues/425
> enable mac terminal install instead of visual installer

- nbs/getting_started.ipynb
Updated link on getting starting page to point to migrating guide instead of migrate module docs.
> Update link to migration guide

- nbdev/clean.py
- nbs/11_clean.ipynb
Note that this isn't yet useful. I'm considering changing `get_config` to read `~/.nbdev/settings.ini` if it exists, then `update` it with `$(pwd)/settings.ini`, then `jupyter_hooks=user` will be useful. @hamelsmu @jph00 what do you think?
> add `user` option to `jupyter_hooks` setting

- nbdev/merge.py
- nbs/06_merge.ipynb
My bad, idk why I thought it wasn't already printing like `git merge` - the reverted commit makes it double print.
> Revert "fix #753"

- nbdev/process.py
- nbs/03_process.ipynb
We were assuming that quarto directives could not have a dash, such that `#|code-fold: true` would not be detected as a quarto directive and would be removed as a nbdev directive.  This fixes that.
> Allow for dash in Quarto directives

- nbdev/clean.py
- nbs/11_clean.ipynb
Jupyter hooks are run from Jupyter's cwd (can be specified or else directory Jupyter was launched from). Test this by launching Jupyter from outside your current project's directory.
When this isn't the same directory as the nbdev repos root directory the settings file is not found.
Because some settings have default values e.g. allowed_metadata_keys the hook doesn't fail when the settings file is missing.
Instead we look at the path of the notebook given to the hook and attempt to find the settings file by
traversing directories upward until we find it or hit root '/'.
@jph00 @seeM
> Hooks ignore settings.ini if Jupyter is started outside nbdev repo

- nbdev/_modidx.py
- nbdev/clean.py
- nbdev/read.py
- nbs/01_read.ipynb
- nbs/11_clean.ipynb
- nbs/tutorial.ipynb
It can be disabled using `clean_ids = False` in user- or project-settings. It can't yet be controlled per-notebook. I'd appreciate some guidance on how best to implement that, and thought it could be done in a follow-up PR.
Also tested by running `nbdev_clean` on fastai, then checking that `rg ' at 0x[0-9a-fA-F]+' nbs` finds nothing.
> Clean `id` from text `repr` outputs to further avoid git merge conflicts

- nbdev/clean.py
- nbs/11_clean.ipynb
For example: https://github.com/fastai/nbdev/pull/790/commits/d2411009c574ff749ac934bd471f2e276b84be6c
> `clean_ids` corrupts string outputs

- nbs/migrating.ipynb
In the migrating notebook, the instruction had a typo, `nbdev_migrate_directives` was changed to `nbdev_migrate`
> fix typo in migrating nb

- nbdev/doclinks.py
- nbs/04b_doclinks.ipynb
- nbs/09_processors.ipynb
> links aren't rendered as code

- nbdev/cli.py
- nbs/10_cli.ipynb
If `doc_path` contains a white space, `nbdev_quarto` crashed as there were no quotes around in the `cd` command.
The same for `nbs_path` and `_render_readme`.
According to the contributing guide every PR should include a test. However, the change in minimal and properly adding a test would require some effort to properly test that the library works with white spaces so I was wondering if it is really needed in this case.
> nbdev commands fail when `doc_path` contains whitespace

- nbdev/cli.py
- nbs/10_cli.ipynb
Run `nbdev_export` removes one step from the minimal hello world tutorial. Here's what the colors looks like:
> Streamline `nbdev_new`: outputs are now in color, you can pass `--lib_name`, and it calls `nbdev_export`

- nbdev/test.py
- nbs/14_test.ipynb
If tests fail in `nbdev_test`, the console output would look something like this,
After the minor fix, it looks like this
> prettify output for `nbdev_test`

- nbdev/cli.py
- nbs/10_cli.ipynb
Quarto config could be customized by custom.yml but it does not work for all settings.
So I propose to add a nbdev settings to prevent overwriting _quarto.yml.
This option as to be `custom_quarto_yml = False` to keep _quarto.yml.
> Add custom_quarto_yml setting

- nbdev/cli.py
- nbs/10_cli.ipynb
This fixes #846 , by changing the order in which the git commands run, such that the local repository is inspected first and the global user's gitconfig is inspected last.  That way, if this fails, we still have _some_ information we can infer on behalf of the user.  
Furthermore, this removes colors as it made the text invisible for me.
cc: @jph00 @seeM
> Change order of git commands during setup: local first, global second & remove colors

- nbs/17_release.ipynb
https://github.com/fastai/nbdev/commit/d32a791a3a6929e9d22fe91e0f48cd330c39a339 accidentally removed `nbs/17_release.ipynb`. This adds it back. I'm not sure if there's a way to get the old git history, maybe [`--ignore-revs-file`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt). cc @hamelsmu @jph00
> revert remove `nbs/17_release.ipynb`

- nbdev/processors.py
- nbs/09b_processors.ipynb
> Make sure `#|exec_doc` triggers an update even when there is no export or show_doc

- nbdev/cli.py
- nbdev/config.py
- nbs/01_config.ipynb
- nbs/12_cli.ipynb
I also removed the end-to-end tests. I don't think they were adding much in the way of tests or docs. We can re-add something like them if these commands turn out to be problematic, which I think is unlikely. cc @hamelsmu @jph00
> run `nbdev_readme` in `nbdev_new`

- nbs/01_Tutorials/01_tutorial.ipynb
The link to the quarto installer in [the tutorial](https://nbdev.fast.ai/01_Tutorials/tutorial.html#install-quarto) is broken. This PR updates the link to where the quarto installer code currently resides.
> Fix broken link in tutorial

- README.md
- nbdev/cli.py
- nbs/12_cli.ipynb
Currently, if you call `nbdev_filter --fname foo` from the command-line it will print to stderr because `nbdev_filter` returns the string, and the `nbdev_filter` binary created by setuptools calls `sys.exit(nbdev_filter(...))` which prints to stderr. This is a minor inconvenience when wanting to do something like `nbdev_filter --fname foo | grep output-file` to test its behaviour. cc @hamelsmu @jph00 
The README change is because I forgot to do `nbdev_prepare` on my last PR
> add `printit` arg to `nbdev_filter` so it can be called with `fname` and still print to stdout

- nbs/11_test.ipynb
Replaced the `fname` flag with `path` at `nbdev_test`s' docs since `fname` does not work with that command anymore.
> `nbdev_test` docs deprecation fix.

- README.md
- nbs/01_Tutorials/03_modular_nbdev.ipynb
- nbs/02_Explanations/config.ipynb
- nbs/getting_started.ipynb
- nbs/styles.css
- fix #949
- add `nbdev.release` and `nbdev.quarto` to "Modular nbdev" page
- keep config explanation updated with `exec_doc`
- styles
- smaller signature and table font
- no striped tables
Before style update:
After:
> Misc docs improvements

- .pre-commit-hooks.yaml
This creates two new hooks for the [pre-commit framework](https://pre-commit.com/): for `nbdev_clean` and `nbdev_export`. They can be used to catch and fix uncleaned and unsynced notebooks, locally, without having to wait for CI. It's also a helpful fallback for people who use editors that we haven't supported yet (e.g. VSCode currently).
It works by defining the `.pre-commit-hooks.yaml` file in our repo root – that's all pre-commit needs! With that, users can easily enable either of these hooks in pre-commit locally.
Here's a rough version of the docs. I haven't included docs in the PR since its still experimental. I'd like for us to try it first then make a call whether to keep and document it. **Note that the hooks will only work once this is merged to master.**
Install pre-commit …
> Experimental: pre-commit hooks

- nbs/01_Tutorials/01_tutorial.ipynb
Since you do not have to enable pages manually, I updated the tutorial to reflect that:
I will explain the workflows of the docs in a separate explanations section that makes show_doc about docs more generally.
cc: @seeM @jph00
> update tutorial "Check out your docs" section re:pages enablement

- nbdev/doclinks.py
- nbdev/maker.py
- nbs/09_API/02_maker.ipynb
- nbs/09_API/04b_doclinks.ipynb
Based on Jeremy's feedback on [#986](https://github.com/fastai/nbdev/issues/986), I've spend today trying to fix it.
**Problem**
The problem was that windows gave windows path outputs, which makes the github actions workflow break (which uses ubuntu-latest and therefore outputs a different path).
**Change**
I've had to add as_posix() to 2 modules:
doclinks (1 time) and maker (2 times)
**Open issue**
My PR has another change, namely "display_name": "Python 3.10.0 64-bit", It's due to kernelspec being allowed als nb metadata_keys in clean_nb:
```
"Clean `nb` from superfluous metadata"
metadata_keys = {"kernelspec", "jekyll", "jupytext", "doc"}
```
Kernelspec could be removed, but I didn't dare, maybe you've left it in for a reason
**Final note**
Now I've had to jump through some hoops since …
> fix #986 use posix path, so windows workflow works

- nbdev/cli.py
- nbdev/migrate.py
- nbs/cli.ipynb
- nbs/migrate.ipynb
> fix: `nbdev_new` encounters 404 error with custom `GH_HOST`

- nbdev/release.py
- nbs/api/release.ipynb
- settings.ini
> fix: `nbdev.release` uses `cfg.lib_name` instead of `cfg.repo`

- nbdev/cli.py
- nbs/api/cli.ipynb
- settings.ini
- Fixes #1038
Note that this requires `ghapi>=1.0.3` for https://github.com/fastai/ghapi/commit/947cab3e5cf7ce2eaad8cacb1eaed658a0cc8806 **which isn't released yet** cc @hamelsmu @jph00.
> `nbdev_new` support for GitHub Enterprise

- nbdev/doclinks.py
- nbdev/quarto.py
- nbs/api/doclinks.ipynb
- nbs/api/quarto.ipynb
- nbs/tutorials/docs_only.ipynb
> Enable Documentation Only Sites With `nbdev` ( + tutorial )

- nbs/tutorials/best_practices.ipynb
fixes #1123 
I don't know how to keep the metadata display name clean for the PR? Is this maybe a feature that `nbdev_clean` needs? I used it but it doesn't "repair" this part.
> fix broken link to vision tutorial

- nbdev/export.py
- nbs/api/export.ipynb
The `black_formatting` option is now calling `str2bool` from fastcore so it's value when retrieved by `cfg.get('black_formatting')` is either 0 or 1, so the code path that does the black formatting is currently inaccessible. This changes the comparison to check against `1`.
> `black_formatting` setting is ignored

- nbs/_quarto.yml
Tbh I'm not really sure why it works, but it does.
Before:
After:
> fix duplicated sections in the sidebar

- nbdev/migrate.py
- nbs/api/migrate.ipynb
closes #1177 
This is what the error message will look like now
```
Traceback (most recent call last):
File "/Users/hamel/github/nbdev/nbdev/migrate.py", line 178, in nbdev_migrate
if f.name.endswith('.md'): migrate_md(f)
File "/Users/hamel/github/nbdev/nbdev/migrate.py", line 162, in migrate_md
txt = fp_md_fm(path)
File "/Users/hamel/github/nbdev/nbdev/migrate.py", line 97, in fp_md_fm
fm = _fp_convert(fm, path)
File "/Users/hamel/github/nbdev/nbdev/migrate.py", line 78, in _fp_convert
if k in fm: fm[k] = _rm_quote(fm[k])
File "/Users/hamel/github/nbdev/nbdev/migrate.py", line 57, in _rm_quote
title = re.search('''"(.*?)"''', s)
File "/opt/anaconda3/lib/python3.9/re.py", line 201, in search
return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
The …
```
> add filename in error message to migrate utility

- nbdev/export.py
- nbs/_quarto.yml
- nbs/api/export.ipynb
This allows me to avoid having `#|default_exp` in singleton notebooks where I just want to export to a script.  This is helpful for people using nbdev for one-off purposes they don't have to worry about what `#|default_exp` means and they can just call nb_export() with an argument if they want
I'm using these changes in #1205
> add parameter for name to nb_export

- nbdev/doclinks.py
- nbs/api/doclinks.ipynb
addresses https://github.com/fastai/nbdev/pull/1210#issuecomment-1307718436:
> afaict this is not the correct fix. The * seemed fine, for single digit prefixes. I think it just needs to be modified to only match the start of the name
fixes #1210
> fix regex in `nbdev.doclinks._nbpath2html`

- nbdev/doclinks.py
- nbs/api/doclinks.ipynb
addresses https://github.com/fastai/nbdev/pull/1211#issuecomment-1307715432:
> Lgtm, except perhaps use a different exception. The one you picked is mainly for abstract classes
> use `ValueError` instead of `NotImplementedError` in `nbdev.doclinks._iter_py_cells`

- nbs/tutorials/tutorial.ipynb
I had some trouble with conda installation because the tutorial was incomplete. I added some instructions that would have helped me.
> add conda install doc to end-to-end tutorial

- nbdev/migrate.py
- nbs/api/migrate.ipynb
Do not sort categories when creating aliases for the URL from fastpages.  I tested it and fastpages/jekyll doesn't sort the categories. see:  https://forums.fast.ai/t/failure-to-migrate-from-fastpages-to-quarto/101466/14?u=hamelsmu
> fix order of categories for migration

- nbdev/serve.py
- nbs/api/serve.ipynb
`proc_nbs` was not copying folders with a prefix of `_`. added an exception for the quarto `extensions` folder.
> copy contents of _extensions folder from nbs

- nbs/tutorials/tutorial.ipynb
This is a docs only change @jph00 
See this discord conversation https://discord.com/channels/689892369998676007/887694559952400424/1065826828981391370
Looks like the GitHub api permissions changed here.  It was always a bit finicky, and I see lots of people getting stuck on this step -- I think it's better to make enabling pages more explicit.
> make enabling gh-pages mandatory

- .pre-commit-hooks.yaml
- nbs/tutorials/pre_commit.ipynb
By fixing the `language` at the pre-commit hook config, this remove the necessity to manually install `nbdev` with pre-commit. 
Before this fix, when using the pre-commit, we have a duplicated `nbdev` environments, one at the pre-commit files (which should be the one used) and another in your environments (which was what was being used). With this fix, the pre-commit will use the files from pre-commit environment -- which will be cached between multiples repo.
Also, this will possibly fix the `nbdev` hook to work with [pre-commit ci](https://pre-commit.ci/).
> Fix nbdev pre-commit hook

- nbdev/quarto.py
- nbs/api/quarto.ipynb
As a follow-up to 898fba89b83387977c71b7fc4ee346ff0c4c8043
> dirs_exist_ok has been moved inside _copytree

- nbdev/release.py
- nbs/api/release.ipynb
There are errors caused by this assert
https://github.com/fastai/nbdev/blob/84c8be199f6ee8ca88118def64021425b7d69928/nbdev/release.py#L282
when previous versions of the distribution tarballs exist in the out directory. This fix deletes old tarballs before calling the conda build command.
> Fix 'nbdev_conda' error when there are prior release tarballs

- nbdev/process.py
- nbs/api/03_process.ipynb
This is to allow people to work with Quarto a bit easier.  People can add a colon after their nbdev directives so it won't break Quarto.  This is the most minimal solution I can think of to unblock folks.   I tested this as follows:
- I added a unit test to make sure directives are still extracted correctly, and did some tests on nbdev
- I tested this on a stand alone quarto project and confirmed that adding a  trailing`:` alleviated Quarto's rendering issue.
This issue keeps cropping on the Quarto side.
This is a workaround for this issue: https://github.com/quarto-dev/quarto-cli/issues/3152
> allow trailing `:` in directives for YAML compliance

- settings.ini
IIUC some breaking change happened recently for py 3.7 so pinning the version, I compared this package version on the passing vs failing CI
> pin ipywidgets version

- nbs/api/11_clean.ipynb
the function is cleaning all notebooks in `config.nbs_path`, not all notebooks in `lib_folder`.
> Correct explanation for fname=None

- nbs/tutorials/tutorial.ipynb
I got stuck at this point of the nbdev End-to-End Walkthrough because I didn't see a gh-pages branch and was unsure if I should create it or if the tutorial was outdated.
Fortunately I decided to refresh the GitHub Pages settings page after a few minutes and saw that it was auto-created. I updated the tutorial to reflect my experience. Feel free to change my explanation in any way.
> Clarify in tutorial about gh-pages branch creation

- nbdev/config.py
- nbs/api/01_config.ipynb
- nbs/api/18_release.ipynb
Should address #1323.
It looks like the documentation is out of date, and recommends some insecure practices with the user's GitHub Personal Access Token. I've made some changes to the `nbs/api/01_config.ipynb` and `nbs/api/18_release.ipynb` notebooks that hopefully address these issues.
> Update GitHub PAT documentation

- nbs/api/02_maker.ipynb
- nbs/api/05_doclinks.ipynb
- nbs/api/07_merge.ipynb
- nbs/api/08_showdoc.ipynb
- nbs/api/17_serve.ipynb
I am a windows os user in South Korea.
When I try to develop a small niche package using nbdev I faced an encoding problem.
As you may know, the default encoding for Korean in Windows OS is cp949. Therefore, when nbdev using Path.read_text from pathlib, their default encoding is cp949 and it causes a decoding error.
The simplest solution that I can figure out is explicitly set encoding for Path.read_text as 'utf-8'.
I believe it will not cause any change for most of users, at the same time it prevent not only Korean but also Japanese or other language users on Windows OS from encoding issues.
I hope this can help more Korean users enhance their productivity by nbdev.
> Fix encoding issue for Windows OS User especially for non-English user

- nbdev/serve.py
- nbs/api/17_serve.ipynb
While I was looking at another issue, I noticed that we are missing parenthesis on one of the .exists function calls.  I pointed this out and Jeremy asked me to put in a PR to fix.  
I'm going to just put in the single change that I mentioned, but I also noticed that the functions in serve aren't really being tested either (at least in isolation).  I was looking at adding some tests, but I think it will be challenging with the current function because we rely on the cfg.config_path. I believe we could make it a lot easier to test by using a cache_path in a similar way to how we use path for nbs currently.  If we made that more flexible, we could create a temporary directory and point to that directory and then ensure that the behavior is how we expect it to be. If there is interest in …
> add parenthesis to serve.proc_nbs

- nbs/api/14_quarto.ipynb
- nbs/blog/posts/2022-08-25-jupyter-git/index.qmd
This PR fixes the broken link in the `jupyter-git` blog.
> fixes #1405

- nbs/api/01_config.ipynb
As stated in the title. Since a main features of `nbdev` is packaging it makes sense to at least include `conda_user` (only knew to add it after running into a complaint from `nbdev_conda`).  I also have a [PR](https://github.com/fastai/nbdev-template/pull/15) on `fastai/nbdev-template`  to handle package data as it seems that it was otherwise ignored.
> added conda_user and package_data to cfg_tail

- nbdev/quarto.py
- nbs/api/14_quarto.ipynb
> Regex Syntax Warning Fix

- nbdev/sync.py
- nbs/api/06_sync.ipynb
A fix for https://github.com/fastai/nbdev/issues/1393. In essence this fixes it by using the complete library path for importing the modidx file rather than just grabbing the lowest level subdirectory from the path.
I'm not entirely sure this is the _right_ fix for the problem, but in the event that it is hopefully it makes your lives very easy.
> Fix sync for nested libraries

- nbdev/cli.py
- nbs/api/13_cli.ipynb
@jph00 
This is the bug that you helped us debug—changed `watch_export` to only export on file modifications to prevent infinite loop on linux.
> Export on modified only bug fix

- nbdev/doclinks.py
- nbs/api/05_doclinks.ipynb
This PR improves the regex detection for doclinks in nbdev. Specifically it now handles parenthesis being included in backticks:
```python
md = """This is a link to `numpy.array` and to `get_config()` but not a link to `foobar`.
And not a link to <code>dict2nb</code>.
This is not a link to `get_config`
"""
print(NbdevLookup('nbdev').linkify(md))
```
```markdown
This is a link to [`numpy.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) and to [`get_config()`](https://nbdev.fast.ai/api/config.html#get_config) but not a link to `foobar`.
And not a link to <code>dict2nb</code>.
This is not a link to `get_config`
```
Additional tests were also added to check against edge cases.
> Improve backtick regex matching for function names

- nbdev/doclinks.py
- nbs/api/05_doclinks.ipynb
This PR adds error handling when attempting to resolve a particular entry point. When attempting to do this resolution, a particular library might throw an error. For example, this happens with a `testcell` throws an error due to how it attempts to look into the IPython registration of magics.
```python
entries = {}
for o in pkg_resources.iter_entry_points(group='nbdev'):
if incl_libs is not None and o.dist.key not in incl_libs: continue
try: entries[o.name] = _qual_syms(o.resolve())
except Exception: pass
```
I've added tests to explicitly mock a good entry point and a bad entry point to test this new functionality:
```python
class BadEntryPoint:
name = 'bad_entry'
dist = type('Dist', (), {'key': 'bad_lib'})()
def resolve(self): raise AttributeError("Simulated error")
class …
```
> Improve error handling in _build_lookup_table entry points

- nbdev/doclinks.py
- nbs/api/05_doclinks.ipynb
This PR updates the logic for the creation of the lookup table for the python symbols in the nbdev docs api for linkifying markdown to prioritize builtins over other standard library modules.
> Change symbols dict logic to prioritize builtins

- nbdev/serve.py
- nbs/api/14_quarto.ipynb
- nbs/api/17_serve.ipynb
IIUC `settings.ini` can be ignored by `_proc_file` which will result it in it not getting copied to the destination directory, which is what we want to avoid because they end up in `_proc` which confuses llms-txt cli, when notebooks are in the root of the repo.
> Fix llmctxissue

- .github/workflows/deploy.yaml
- .github/workflows/test.yaml
- nbdev/cli.py
- nbs/api/13_cli.ipynb
fix: update workflow paths from fastai to answerdotai
Fixes #1495
Problem:
When using `nbdev_new` on GitHub Enterprise accounts, the initial workflow fails because it's trying to use `fastai/workflows` which now redirects to `answerdotai/workflows`. While regular GitHub accounts follow this redirect automatically, Enterprise accounts are more strict about redirects, causing the workflow to fail.
Changes:
- Updated template source in `nbdev_new` from `fastai` to `answerdotai`
- Points to nbdev-template repository which will have updated workflow paths (see answerdotai/nbdev-template#20)
Note: This fix requires both this PR and answerdotai/nbdev-template#20 to be merged to be fully effective.
> fix: update workflow paths from fastai to answerdotai

- nbdev/showdoc.py
- nbs/api/08_showdoc.ipynb
- settings.ini
Part of moving dispatch and transform from fastcore to fasttransform (see [here](https://github.com/AnswerDotAI/fasttransform/issues/3)).
This PR removes the use of `fastcore.dispatch.TypeDispatch` and replaces it with `plum.Function`.
This needs to be done before merging [the PR](https://github.com/AnswerDotAI/fastcore/pull/669) that removes dispatch and transform from fastcore. Because as long as nbdev depends on `fastcore.dispatch` removing the module will cause [fastcore's integration tests to break](https://github.com/AnswerDotAI/fastcore/actions/runs/13637679980/job/38120313432?pr=669).
Open questions:
> Use plum dispatch
